name: Code Style Check


on: 
  push:
    branches:
      - dev
  


  pull_request:
    branches:
      - dev

jobs:
  checkstyle_project:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repo
        uses: actions/checkout@v2
      
      - name: Set version Java
        uses: actions/setup-java@v2
        with:
          java-version: '21'
      
      - name: Install dependencies
        run: 
      
      - name: Run linter
        run: |
          